# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 497)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labstres = QtWidgets.QPushButton(self.centralwidget)
        self.labstres.setGeometry(QtCore.QRect(240, 120, 331, 111))
        self.labstres.setStyleSheet("background-image: url(:/gato/lab33.png);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.labstres.setText("")
        self.labstres.setObjectName("labstres")
        self.labsuno = QtWidgets.QPushButton(self.centralwidget)
        self.labsuno.setGeometry(QtCore.QRect(240, 350, 331, 121))
        self.labsuno.setStyleSheet("background-image: url(:/gato/lab1.png);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.labsuno.setText("")
        self.labsuno.setObjectName("labsuno")
        self.labsdos = QtWidgets.QPushButton(self.centralwidget)
        self.labsdos.setGeometry(QtCore.QRect(410, 240, 161, 101))
        self.labsdos.setStyleSheet("background-image: url(:/gato/lab222.png);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.labsdos.setText("")
        self.labsdos.setObjectName("labsdos")
        self.bodega = QtWidgets.QPushButton(self.centralwidget)
        self.bodega.setGeometry(QtCore.QRect(240, 240, 161, 101))
        self.bodega.setStyleSheet("background-image: url(:/gato/bodega.png);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"color: rgb(255, 0, 0);")
        self.bodega.setText("")
        self.bodega.setObjectName("bodega")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 340, 91, 51))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(230, 230, 81, 51))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(240, 120, 81, 41))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 240, 71, 31))
        self.label_8.setStyleSheet("background-image: url(:/gato/l2.png);")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 130, 161, 131))
        self.label_11.setObjectName("label_11")
        self.encendidotv = QtWidgets.QPushButton(self.centralwidget)
        self.encendidotv.setGeometry(QtCore.QRect(40, 250, 21, 21))
        self.encendidotv.setStyleSheet("background-image: url(:/gato/encendido.png);")
        self.encendidotv.setText("")
        self.encendidotv.setObjectName("encendidotv")
        self.canalmas = QtWidgets.QPushButton(self.centralwidget)
        self.canalmas.setGeometry(QtCore.QRect(70, 250, 21, 21))
        self.canalmas.setStyleSheet("background-image: url(:/gato/arriba - copia (2).png);")
        self.canalmas.setText("")
        self.canalmas.setObjectName("canalmas")
        self.canalmenos = QtWidgets.QPushButton(self.centralwidget)
        self.canalmenos.setGeometry(QtCore.QRect(100, 250, 21, 21))
        self.canalmenos.setStyleSheet("background-image: url(:/gato/arriba - copia.png);")
        self.canalmenos.setText("")
        self.canalmenos.setObjectName("canalmenos")
        self.volumenmenos = QtWidgets.QPushButton(self.centralwidget)
        self.volumenmenos.setGeometry(QtCore.QRect(130, 250, 21, 21))
        self.volumenmenos.setStyleSheet("background-image: url(:/gato/arriba - copia (3).png);")
        self.volumenmenos.setText("")
        self.volumenmenos.setObjectName("volumenmenos")
        self.volumenmas = QtWidgets.QPushButton(self.centralwidget)
        self.volumenmas.setGeometry(QtCore.QRect(160, 250, 21, 21))
        self.volumenmas.setStyleSheet("background-image: url(:/gato/arriba.png);\n"
"")
        self.volumenmas.setText("")
        self.volumenmas.setObjectName("volumenmas")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 791, 601))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 20, 91, 91))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 10, 131, 101))
        self.label_3.setObjectName("label_3")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(80, 110, 61, 41))
        self.label_14.setObjectName("label_14")
        self.temperatura = QtWidgets.QLineEdit(self.centralwidget)
        self.temperatura.setGeometry(QtCore.QRect(620, 450, 101, 21))
        self.temperatura.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.temperatura.setObjectName("temperatura")
        self.luz = QtWidgets.QLineEdit(self.centralwidget)
        self.luz.setGeometry(QtCore.QRect(620, 390, 101, 21))
        self.luz.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.luz.setObjectName("luz")
        self.salen = QtWidgets.QLineEdit(self.centralwidget)
        self.salen.setGeometry(QtCore.QRect(620, 310, 101, 21))
        self.salen.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.salen.setObjectName("salen")
        self.entran = QtWidgets.QLineEdit(self.centralwidget)
        self.entran.setGeometry(QtCore.QRect(620, 180, 101, 21))
        self.entran.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.entran.setObjectName("entran")
        self.adentro = QtWidgets.QLineEdit(self.centralwidget)
        self.adentro.setGeometry(QtCore.QRect(620, 240, 101, 21))
        self.adentro.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.adentro.setObjectName("adentro")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(610, 140, 111, 41))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(580, 410, 181, 41))
        self.label_16.setObjectName("label_16")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(580, 100, 161, 41))
        self.label_20.setObjectName("label_20")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(600, 200, 131, 41))
        self.label_18.setObjectName("label_18")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(610, 270, 111, 41))
        self.label_21.setObjectName("label_21")
        self.acceso = QtWidgets.QLineEdit(self.centralwidget)
        self.acceso.setGeometry(QtCore.QRect(100, 470, 101, 21))
        self.acceso.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Segoe UI Black\";\n"
"font: 75 8pt \"Myanmar Text\";\n"
"background-image: url(:/gato/-clip-art_csp45647522.jpg);")
        self.acceso.setObjectName("acceso")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(20, 450, 81, 51))
        self.label_22.setStyleSheet("border-image: url(:/gato/puerta.png);")
        self.label_22.setObjectName("label_22")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 10, 481, 101))
        self.label_9.setObjectName("label_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 310, 121, 101))
        self.label_2.setObjectName("label_2")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(80, 270, 101, 61))
        self.label_10.setObjectName("label_10")
        self.encendidotv_2 = QtWidgets.QPushButton(self.centralwidget)
        self.encendidotv_2.setGeometry(QtCore.QRect(40, 410, 21, 21))
        self.encendidotv_2.setStyleSheet("background-image: url(:/gato/encendido.png);")
        self.encendidotv_2.setText("")
        self.encendidotv_2.setObjectName("encendidotv_2")
        self.canalmas_2 = QtWidgets.QPushButton(self.centralwidget)
        self.canalmas_2.setGeometry(QtCore.QRect(70, 410, 21, 21))
        self.canalmas_2.setStyleSheet("background-image: url(:/gato/arriba - copia (2).png);")
        self.canalmas_2.setText("")
        self.canalmas_2.setObjectName("canalmas_2")
        self.canalmenos_2 = QtWidgets.QPushButton(self.centralwidget)
        self.canalmenos_2.setGeometry(QtCore.QRect(100, 410, 21, 21))
        self.canalmenos_2.setStyleSheet("background-image: url(:/gato/arriba - copia.png);")
        self.canalmenos_2.setText("")
        self.canalmenos_2.setObjectName("canalmenos_2")
        self.volumenmenos_2 = QtWidgets.QPushButton(self.centralwidget)
        self.volumenmenos_2.setGeometry(QtCore.QRect(130, 410, 21, 21))
        self.volumenmenos_2.setStyleSheet("background-image: url(:/gato/arriba - copia (3).png);")
        self.volumenmenos_2.setText("")
        self.volumenmenos_2.setObjectName("volumenmenos_2")
        self.volumenmas_2 = QtWidgets.QPushButton(self.centralwidget)
        self.volumenmas_2.setGeometry(QtCore.QRect(160, 410, 21, 21))
        self.volumenmas_2.setStyleSheet("background-image: url(:/gato/arriba.png);\n"
"")
        self.volumenmas_2.setText("")
        self.volumenmas_2.setObjectName("volumenmas_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(600, 330, 191, 61))
        self.label_12.setObjectName("label_12")
        self.label.raise_()
        self.labstres.raise_()
        self.labsuno.raise_()
        self.labsdos.raise_()
        self.bodega.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_11.raise_()
        self.encendidotv.raise_()
        self.canalmas.raise_()
        self.canalmenos.raise_()
        self.volumenmenos.raise_()
        self.volumenmas.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_14.raise_()
        self.temperatura.raise_()
        self.luz.raise_()
        self.salen.raise_()
        self.entran.raise_()
        self.adentro.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.label_20.raise_()
        self.label_18.raise_()
        self.label_21.raise_()
        self.acceso.raise_()
        self.label_22.raise_()
        self.label_9.raise_()
        self.label_2.raise_()
        self.label_10.raise_()
        self.encendidotv_2.raise_()
        self.canalmas_2.raise_()
        self.canalmenos_2.raise_()
        self.volumenmenos_2.raise_()
        self.volumenmas_2.raise_()
        self.label_12.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/l1.png\"/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/bode.png\"/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/l3.png\"/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/televisor.png\"/></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/585940.png\"/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/fcbi.png\"/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/unilla.png\"/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/tvtexto.png\"/></p></body></html>"))
        self.temperatura.setText(_translate("MainWindow", "15"))
        self.luz.setText(_translate("MainWindow", "Noche"))
        self.salen.setText(_translate("MainWindow", "17.2"))
        self.entran.setText(_translate("MainWindow", "17.2"))
        self.adentro.setText(_translate("MainWindow", "17.2"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/cooltext351535095367733.png\"/></p></body></html>"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/cooltext351534306177371.png\"/></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/cooltext351534278526578.png\"/></p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/cooltext351534293424501 (1).png\"/></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/cooltext351534862494221.png\"/></p></body></html>"))
        self.acceso.setText(_translate("MainWindow", "abierto"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/titulo final.png\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/tv2.png\"/></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/tvtexto2.png\"/></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/gato/ilu.png\"/></p></body></html>"))
import prefinalimg


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
